/**:
  ros__parameters:
    serial_write: "/dev/ttyACM0"
    serial_read: "/dev/ttyACM1"
    drivetrain_code: "0"
    stepper_code: "1"

    button_list: ['bb', 'gb', 'rb']
    bb: "table1"
    gb: "table2"
    rb: "table3"
