/**:
  ros__parameters:
    serial_port_1: "/dev/ttyACM0"
    serial_port_2: "/dev/ttyACM1"
    serial_port_3: "/dev/ttyACM2"
    drivetrain_code: "0"
    stepper_code: "1"

    button_list: ['bb', 'gb', 'rb']
    bb: "table1"
    gb: "table2"
    rb: "table3"
